name: algolia
version: 0.1.7
authors: 
  - Nayan Hathiwala (Knoxpo) <nhathiwala@knoxpo.com>
description: >
   Algolia is a pure dart SDK, wrapped around Algolia REST API for easy implementation for your Flutter or Dart projects.
homepage: https://github.com/knoxpo/dart_algolia

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  http: ^0.13.1
  uuid: ^3.0.4

dev_dependencies:
  test: ^1.0.0
